### ISSUE TITLE
In examples "Show preferences" doesn't have a back button

### ISSUE THREAD

**Issue by MartinSStewart** [Orange-OpenSource/elm-advanced-grid#4]
If I click the "Show preferences" button in the example tables, there doesn't seem to be a way to return to the table I was looking at.

**Comment by PascalLeMerrer** [comment]
The close button is on the top right of the preference panel.
Maybe it's not visible enough (light gray, darker on hover)?

**Comment by MartinSStewart** [comment]
Oh, there it is. Yes, I would recommend making it darker.

**Comment by MartinSStewart** [comment]
Alternatively you could make the "show preferences" button toggle the preferences visibility. The text would change to "hide preferences" while the preferences are visible.

**Comment by PascalLeMerrer** [comment]
Yep, but this button is used only for the demo. So maybe I should do both. Thanks for your feedback!

**Comment by PascalLeMerrer** [comment]
Fixed by https://github.com/Orange-OpenSource/elm-advanced-grid/commit/c901b0c2be75b6ca9d3bb1c2aae8aa0cfca61994 and c58c0f3d0b0edb2b49b70d9bf3afcc049c2a9a95
